/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
	interface Env {
		ENVIRONMENT: "production";
		AGENT_NAME: "Colby Remodel Agent";
		DB: D1Database;
		PROJECT_KV: KVNamespace;
		PROJECT_WORKFLOW: Workflow;
	}
}

interface Env extends Cloudflare.Env {}

type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};

declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "AGENT_NAME">> {}
}
